# Dockerfile.backend

# 使用 Node.js 官方镜像作为基础镜像
FROM node:14

# 设置工作目录
WORKDIR /app

# 复制 package.json 和 package-lock.json
COPY backend/package*.json ./

# 安装依赖项
RUN npm install

# 复制所有后端项目文件到工作目录
COPY backend ./

# 公开后端服务的端口
EXPOSE 8000

# 启动后端服务
CMD ["node", "index.js"]
