# Stage 1: Build frontend
FROM node:16
WORKDIR /app/frontend
COPY ./frontend/package*.json ./
RUN npm install
COPY ./frontend/.env.production ./
RUN npm install -g react-scripts
COPY ./frontend .
RUN npm run build-prod

# Stage 2: Build backend
WORKDIR /app/backend
RUN rm -rf node_modules
COPY ./backend/package*.json ./
# Install build dependencies for node-gyp and sqlite3
RUN apt-get update && apt-get install -y build-essential python3
RUN apt-get update && apt-get install -y libsqlite3-dev

# Install Node.js global packages and project dependencies
RUN npm install -g node-gyp
RUN npm install && npm rebuild sqlite3 --build-from-source --arch=x64 --platform=linux

COPY ./backend .

# Final stage: Run the application
WORKDIR /app/backend

# Expose necessary ports
EXPOSE 8000

# Start the backend that serves the frontend
CMD ["sh", "-c", "cd /app/backend && node index.js"]